MiAmor Vet/miamorvet/miamorvet/urls.py
from django import views
from django.contrib import admin
from django.urls import path,include
from pet import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('pets/', include("pet.urls")),
    path('user/',include("user.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html") , name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MiAmor Vet/miamorvet/pet/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views


app_name = "pet"

urlpatterns = [
  path('dashboard/', views.dashboard, name="dashboard"),
  path('addpet/', views.addPet, name="addpet"),
  path('pet/<int:id>', views.detail, name="detail"),
  path('update/<int:id>', views.updatePet, name="update"),
  path('delete/<int:id>', views.deletePet, name="delete"),
  path('', views.pets, name="pets"),

]

MiAmor Vet/miamorvet/user/urls.py
from django.urls import path 
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "user"


urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('profile/',views.profileUser,name="profile"),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MiAmor Vet/miamorvet/pet/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Pet(models.Model):
    author = models.ForeignKey("auth.User",on_delete= models.CASCADE, verbose_name='Yazar')
    name = models.CharField(max_length=50, verbose_name="İsim")
    type = models.CharField(max_length=50, verbose_name="Tür")
    genus = models.CharField(max_length=50, verbose_name="Cins")
    age = models.IntegerField(verbose_name="Yaş")
    explanation = RichTextField(verbose_name="Açıklama")
    pet_image = models.FileField(blank=True,null=True,verbose_name="Fotoğraf Yükle")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturma Tarihi")

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_date']

MiAmor Vet/miamorvet/pet/forms.py
from django import forms
from .models import Pet

class PetForm(forms.ModelForm):
    class Meta: 
        model = Pet
        fields = ["name","type","genus","age","explanation","pet_image"]

MiAmor Vet/miamorvet/pet/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from .forms import PetForm
from .models import Pet


def pets(request):

    keyword = request.GET.get("keyword")

    if keyword:
        pets = Pet.objects.filter(name__contains = keyword)
        return render(request,"pets.html",{"pets":pets})

    pets = Pet.objects.all()

    context = {
        "pets" : pets
    }

    return render(request,"pets.html",context)



def index(request):
    context = {

    }

    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    pets = Pet.objects.filter(author = request.user)
    context = {
        "pets" : pets
    }
    return render(request,"dashboard.html",context)

@login_required(login_url="user:login")
def addPet(request):
    form = PetForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        pet = form.save(commit=False)
        pet.author = request.user
        pet.save()
        messages.success(request,"Hayvan Başarılı Bir Şekilde Kaydedildi!")
        return redirect("pet:dashboard")

    context = {
        "form" : form
    }
    return render(request,"addpet.html",context)

@login_required(login_url="user:login")
def detail(request,id):
    pet = get_object_or_404(Pet,id=id)

    context = {
        "pet" : pet
    }

    return render(request,"detail.html",context)

@login_required(login_url="user:login")
def updatePet(request,id):

    pet = get_object_or_404(Pet,id=id)
    form = PetForm(request.POST or None, request.FILES or None,instance=pet)
    if form.is_valid():
        pet = form.save(commit=False)
        if request.user == pet.author or request.user.is_superuser:
            pet.save()
        else:
            messages.warning(request,"Seçilen Hayvanı Güncellemeye Yetkiniz Yok!")
            return redirect("pet:dashboard")
        messages.success(request,"Hayvan Başarılı Bir Şekilde Güncellendi")
        return redirect("pet:dashboard")

    context = {
        "form" : form
    }

    return render(request,"update.html",context)

@login_required(login_url="user:login")
def deletePet(request,id):
    pet = get_object_or_404(Pet,id=id)
    if request.user == pet.author.username or request.user.is_superuser:
        pet.delete()
    else:
        messages.warning(request,"Seçilen Hayvanı Silmeye Yetkiniz Yok!")
        return redirect("pet:dashboard")

    messages.success(request,"Kayıt Başarılı Bir Şekilde Silindi")   

    return redirect("pet:dashboard")     

MiAmor Vet/miamorvet/templates/about.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}

<section id="about">
  <div class="container">

    <header class="section-header">
      <h3 align="center">Hakkımızda</h3>
      <hr>
      <p>MiAmor Vet <b>10 yıllık</b> hizmet tecrübesiyle, canlarınıza sevgisini aktarıyor.</p>
    </header>

    <div class="row about-container">

      <div class="col-lg-6 content order-lg-1 order-2">
        <p>
          Uzman veteriner hekim kadrosu ve bitmek bilmeyen şefkati ile hayvanlarınız için en iyisini düşünüyoruz. Gelişmiş teknikler ve 
          araçlar kullanarak, klinik sıkıntıları tespit ediyor ve tedavisini en iyi şekilde gerçekleştiriyoruz. 
        </p>
        <br>
      </div>
     
      <div class="col-lg-6 background order-lg-2 order-1 wow fadeInUp">
        <img src=" {% static 'images/about-img.svg' %}" class="img-fluid" alt="">
      </div>
    </div>
    <div class="row about-extra">
      <div class="col-lg-6 wow fadeInUp">
        <img src=" {% static 'images/about-extra-1.svg' %}" class="img-fluid" alt="">
      </div>
      <div class="col-lg-6 wow fadeInUp pt-5 pt-lg-0">
        <br><br>
        <h4>Siz işteyken aklınız hayvanınınzda mı kalıyor? </h4>
        <br>
        <p>
          Çalışırken aklınız evdeki hayvanınızda ise, MiAmor Vet'in hayanlarınız için 
          kliniğinde bulunan özel vakit geçirme alanları ile diğer canlılarla vakit geçirip, 
          beslenmesi ve diğer ihtiyaçlarını karşılayabileceği PetPark hizmeti hakkında bilgi alın.
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock  %}

MiAmor Vet/miamorvet/templates/addpet.html
{% extends "layout.html" %}

{% block body %}
  
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3 align="center">Hayvan Ekle</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form | crispy }}

            <div class="border-top pt-3">
                <small class="text-muted">
                   <i>Önerilen Resim Boyutu (1920x1080)</i>
                </small>
            </div>
            <br>
            <button type="submit" class="btn btn-outline-info">Hayvan Ekle</button>
        </form>
    </div>
  </div>

{% endblock body %}

MiAmor Vet/miamorvet/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Hayvanlarım : </h3>
<hr>
<p>Merhaba <i>{{request.user.first_name}} {{request.user.last_name}},</i> canların burada!</p>
<hr>
<a class="btn btn-success" href="{% url 'pet:addpet' %}">Hayvan Ekle</a>
<br><br>

{% if pets %}

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Adı</th>
        <th scope="col">Türü</th>
        <th scope="col">Cinsi</th>
        <th scope="col">Yaşı</th>
        <th scope="col">Kayıt Tarihi</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>

        {% for pet in pets  %}

        <tr>
            <th scope="row">{{pet.id}}</th>
            <td><a href="{% url 'pet:detail' pet.id %}">{{pet.name}}</a></td>
            <td>{{pet.type}}</td>
            <td>{{pet.genus}}</td>
            <td>{{pet.age}}</td>
            <td>{{pet.created_date}}</td>
            <td><a class="btn btn-success" href="{% url 'pet:update' pet.id %}">Güncelle</a></td>
            <td><a class="btn btn-danger" href="{% url 'pet:delete' pet.id %}">Kaydı Sil</a></td>
          </tr>
          
        {% endfor %}

    
      
     
    </tbody>
  </table>
  
{% else %}

<div class="alert alert-danger">Henüz Kayıtlı Bir Hayvanınız Bulunmuyor!</div>
  
{% endif %}
  
{% endblock body %}

MiAmor Vet/miamorvet/templates/detail.html
{% extends "layout.html" %}
{% load static %}
{% block body %}


<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <article>
                <header class="mb-4">
                    <h3 class="fw-bolder mb-1">Hayvanın Adı : {{pet.name}}</h3> <hr>
                    <div class="text-muted fst-italic mb-2">
                    
                    <h5>Hayvan Bilgileri : </h5>
                    Türü : {{pet.type}} <br>
                    Cinsi : {{pet.genus}} <br>
                    Yaşı : {{pet.age}} <br>
                    Kayıt Tarihi : {{pet.created_date}} <br> 
                    <hr>
                    <h5>Sahip Bilgileri : </h5>
                    Hayvan Sahibi : {{pet.author.first_name}} {{pet.author.last_name}} <br>
                    Telefon : {{pet.author.profile.phone}} <br>
                    Mail : {{pet.author.email}} <br>
                   
                </div>
                </header>
               {% if pet.pet_image %}
               <figure class="mb-4"><img class="img-fluid rounded" width="50%" src="{{pet.pet_image.url}}" alt="{{pet.name}}" /></figure>
               {% else %}
               <figure class="mb-4"><img class="img-fluid rounded" width="50%" src="{% static 'images/default-image.jpg' %}" alt="{{pet.name}}" /></figure>
               {% endif %}
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{pet.name}} Hakkında Açıklama : {{pet.explanation | safe}}</p>
                </section>
            </article>
            <hr>
        
{% endblock body %}

MiAmor Vet/miamorvet/templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block body %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/carousel.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/index.css' %}">



<main role="main">

    <div class="carousel slide" data-ride="carousel" id="carouselExampleIndicators">
      <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#carouselExampleIndicators"></li>
        <li data-slide-to="1" data-target="#carouselExampleIndicators"></li>
        <li data-slide-to="2" data-target="#carouselExampleIndicators"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img alt="First slide" class="d-block w-100" src="{% static 'images/slider1.jpg' %}">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="animated bounceInRight" style="animation-delay: 1s">MiAmor Vet</h5>
            <p class="animated bounceInLeft" style="animation-delay: 2s">
                MiAmor Vet 10 yıllık hizmet tecrübesiyle, canlarınıza sevgisini aktarıyor.</p>
              {% if request.user.is_authenticated %}
                
              {% else %}
              <p class="animated bounceInRight" style="animation-delay: 3s"><a href="{% url 'user:register' %}">Hemen Kayıt Ol!</a></p> 
              {% endif %}
          </div>
        </div>
        <div class="carousel-item">
          <img alt="Second slide" class="d-block w-100" src="{% static 'images/slider2.jpg' %}">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="animated slideInDown" style="animation-delay: 1s">Neden biz?</h5>
            <p class="animated fadeInUp" style="animation-delay: 2s">Uzman veteriner hekim kadrosu ve bitmek bilmeyen şefkati ile hayvanlarınız için en iyisini düşünüyoruz.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img alt="Third slide" class="d-block w-100" src="{% static 'images/slider3.jpg' %}">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="animated zoomIn" style="animation-delay: 1s">Kliniğimiz</h5>
            <p class="animated fadeInLeft" style="animation-delay: 2s">
              Kliniğimizde son teknolojik cihazlar ve teknikler kullanarak canlarınızın klinik sıkıntılarını tespit ediyor ve tedavisini en iyi şekilde gerçekleştiriyoruz. </p>
          </div>
        </div>
      </div><a class="carousel-control-prev" data-slide="prev" href="#carouselExampleIndicators" role="button"><span aria-hidden="true" class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" data-slide="next" href="#carouselExampleIndicators" role="button"><span aria-hidden="true" class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
    </div> 
</main>

<section id="services" class="section-bg">
    <div class="container">

      <header class="section-header">
        <h3 align="center">MiAmor Vet</h3>
        <p align="center">Uzman veteriner hekim kadrosu ve bitmek bilmeyen şefkati ile hayvanlarınız için en iyisini düşünüyoruz. Gelişmiş teknikler ve araçlar kullanarak, klinik sıkıntıları tespit ediyor ve tedavisini en iyi şekilde gerçekleştiriyoruz.</p>
      </header>
      <br><br>
      <div class="row">
        <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-duration="1.4s">
          <div class="box">
            <div class="icon"><i class="fas fa-sign-in-alt" ></i></div>
            <h4 class="title"><a href="{% url 'user:register' %}">Aramıza Katıl</a></h4>
            <p class="description">Klinik imkanlarımızdan ve online sistemimizden faydalanmak için hemen kayıt olun.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-duration="1.4s">
          <div class="box">
            <div class="icon"><i class="fas fa-cat" style="color: #e9bf06;"></i></div>
            <h4 class="title"><a href="{% url 'pet:dashboard' %}">Her Zaman Yanı Başınızda</a></h4>
            <p class="description">Hayvanlarınızı klinik sistemimize kayıt edin ve klinik süreçten her daim haberdar olun.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
          <div class="box">
            <div class="icon"><i class="fas fa-sort-amount-up-alt" style="color: #3fcdc7;"></i></div>
            <h4 class="title"><a href="#">Kolay Arayüz</a></h4>
            <p class="description">Basit arayüz sistemimiz ile hayvanlarınızı kolayca kayıt edebilirsiniz.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
          <div class="box">
            <div class="icon"><i class="fas fa-user-md" style="color:#41cf2e;"></i></div>
            <h4 class="title"><a href="{% url 'about' %}">Uzman Kadro</a></h4>
            <p class="description">Kliniğimizde gelişmiş teknikler kullanarak canlarınızın klinik sıkıntılarını tedavi ediyoruz.</p>
          </div>
        </div>

      </div>

    </div>
  </section>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script> 
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

{% endblock body %}

MiAmor Vet/miamorvet/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="{%  static 'images/favicon.ico' %}">
    <title>MiAmor Vet</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    
    <div style="margin-top : 50px; margin-bottom:50px;" class="container">
        {% if messages %}
       
            {% for message in messages %}
            {% if message.tags == "info" %}
            <div class = "alert alert-danger"> {{ message }} </div>
            {% else %}
            <div class = "alert alert-{{ message.tags }}"> {{ message }} </div>
            {% endif %}
          
            {% endfor %}
       
        {% endif %}

        {% block body %}


          
        {% endblock body %}

    </div>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
</body>
</html>

MiAmor Vet/miamorvet/templates/login.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
{% load crispy_forms_tags %}

<div style="text-align: center;">
<img src="{% static 'images/miamor-logo.png' %}" widht="75px" height="75px"  alt="MiAmor Vet">
</div>
<br>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{form | crispy }}
            <button type="submit" class="btn btn-outline-info">Giriş Yap</button>
        </form>
        <br>
        <div class="border-top pt-3">
            <small class="text-muted">
                Henüz Hesabınız Yok Mu? <a class="ml-2" href="{% url 'user:register' %}">Hemen Kayıt Ol</a>
            </small>
            &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
            <small class="text-muted">
                Şifreni mi Unuttun? <a class="ml-2" href="{% url 'password_reset' %}">Şifreni Sıfırla</a>
            </small>
        </div>
    </div>
  </div>

{% endblock body %}

MiAmor Vet/miamorvet/templates/password_reset.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Şifreni Sıfırla</legend>
			{{ form|crispy }}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Sıfırlama Talebi Gönder</button>
		</div>
	</form>
</div>

{% endblock body %}

MiAmor Vet/miamorvet/templates/password_reset_complete.html
{% extends "layout.html" %}

{% block body %}

<div class="alert alert-info">
    Şifreniz değiştirildi!
</div>
&ensp;<a href="{% url 'user:login' %}">Giriş Yapın</a>
  
{% endblock body %}

MiAmor Vet/miamorvet/templates/password_reset_confirm.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Şifreni Sıfırla</legend>
			{{ form|crispy }}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Sıfırla</button>
		</div>
	</form>
</div>
  
{% endblock body %}

MiAmor Vet/miamorvet/templates/password_reset_done.html
{% extends "layout.html" %}
{% load static %}

{% block body %}

<div class="alert alert-info">
    Girdiğiniz e-postaya ait bir hesap varsa şifre sıfırlama talebi kısa bir süre içinde e-postanıza iletilecektir. Eğer herhangi bir e-posta 
    almazsanız lütfen girdiğiniz e-posta adresinizden emin olun ve spam klasörünüzü kontrol etmeyi unutmayın.
</div>
  
{% endblock body %}

MiAmor Vet/miamorvet/templates/pets.html
{% extends "layout.html" %}
{% load static %}

{% block body %}

<h3 align="center">Kliniğe Kayıtlı Hayvanlar : </h3>

<div class="body search">
    <div class="input-group m-b-0">
      <form>
        {% csrf_token %}
        <input type="text" maxlength="64" name="keyword" placeholder="Hayvan Ara..">
        <button type="submit" class="btn btn-outline-info">Ara</button>
    </form>                             
    </div>
<hr>

{% if pets %}


<div class="container">
    <div class="row">   
       
{% for pet in pets %}
<div class="col-lg-3 d-flex align-items-stretch">
<div class="card" style="width: 18rem;">
      <div class="img-post">
        <a href="{% url 'pet:detail' pet.id %}">
        {% if pet.pet_image %}
         <img src="{{pet.pet_image.url}}" class="card-img-top" alt="{{pet.name}}" height="200">
        {% else %}
         <img src="{% static 'images/default-image.jpg' %}" class="card-img-top" alt="{{pet.name}}" height="200">
        {% endif %}
        </a>
      </div>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'pet:detail' pet.id %}">Hayvanın Adı : {{pet.name}}</a></h5>
        <hr>
            <h7 class="card-subtitle mb-2 text-muted">
                Cinsi : {{pet.genus}} <br>
                Kayıt Tarihi : {{pet.created_date}} <br> 
            </h7>
            <hr>
        <p class="card-text">{{pet.name}} Hakkında : {{pet.explanation | truncatewords:8 | safe}}</p>
        <a href="{% url 'pet:detail' pet.id %}" class="btn btn-success"><i class="fas fa-info-circle"></i> Hayvan Detayı</a>
        <br><br>
        <a class="btn btn-info" href="{% url 'pet:update' pet.id %}"><i class="far fa-edit"></i> Kaydı Güncelle</a>
        <br><br>
        <a class="btn btn-danger" href="{% url 'pet:delete' pet.id %}"><i class="fas fa-trash"></i> Kaydı Sil</a>
      </div>
    </div>
</div>

{% endfor %}
    </div>
</div>

{% else %}

<div class="alert alert-danger">Kayıtlı Bir Hayvan Bulunamadı</div>
  
{% endif %}

{% endblock body %}

MiAmor Vet/miamorvet/templates/profile.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
{% load static %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<div class="container emp-profile">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        {% if user.profile.avatar %}
                        <div class="profile-img">
                            <img src="{{ user.profile.avatar.url }}" width="275" height="300" alt=""/>
                        </div>
                        {% else %}
                        <div class="profile-img">
                            <img src="{% static 'images/default.jpg' %}" width="275" height="300"  alt=""/>
                        </div>
                          
                        {% endif %}
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{request.user.first_name}} {{request.user.last_name}}
                                    </h5>
                                <hr>
                                <h5>Hakkımda:</h5>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Kullanıcı Adı:</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.username}}</p>
                                    </div>
                                </div> 
                               
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>İsim Soyisim:</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.first_name}} {{user.last_name}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Email:</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.email}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Telefon:</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.profile.phone}}</p>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
                
                </div>
            </form>       
            <br>
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Bilgilerini Güncelle</legend>
                {{p_form|crispy}}
                {{u_form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Güncelle</button>
            </div>
        </form>
     </div>
  
{% endblock body %}

MiAmor Vet/miamorvet/templates/register.html
{% extends 'layout.html' %}
{% load static %}


{% block body %}
{% load crispy_forms_tags %}

<div style="text-align: center;">
    <img src="{% static 'images/miamor-logo.png' %}" widht="75px" height="75px"  alt="MiAmor Vet">
    </div>
    <br>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{form | crispy }}
            <br>
            <button type="submit" class="btn btn-outline-info">Kayıt Ol</button>
        </form>
        <br>
        <div class="border-top pt-3">
            <small class="text-muted">
                Hesabınız Var Mı? <a class="ml-2" href="{% url 'user:login' %}">Hemen Giriş Yap</a>
            </small>
        </div>
    </div>
  </div>

{% endblock body %}