MiAmor Vet/miamorvet/miamorvet/urls.py
from django import views
from django.contrib import admin
from django.urls import path,include
from pet import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('pets/', include("pet.urls")),
    path('user/',include("user.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html") , name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MiAmor Vet/miamorvet/pet/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views


app_name = "pet"

urlpatterns = [
  path('dashboard/', views.dashboard, name="dashboard"),
  path('addpet/', views.addPet, name="addpet"),
  path('pet/<int:id>', views.detail, name="detail"),
  path('update/<int:id>', views.updatePet, name="update"),
  path('delete/<int:id>', views.deletePet, name="delete"),
  path('', views.pets, name="pets"),

]

MiAmor Vet/miamorvet/user/urls.py
from django.urls import path 
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "user"


urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('profile/',views.profileUser,name="profile"),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MiAmor Vet/miamorvet/templates/includes/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">

<nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
    <a class="navbar-brand" href="/"><img class="logo" src="{% static 'images/miamor-logo.png' %}" alt="MiAmor Vet"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}"><i class="fas fa-home"></i>&ensp;Anasayfa</a>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pet:pets' %}"><i class="fas fa-paw"></i>&ensp;Canlarımız</a>
        </li>
        {% else %}
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}"><i class="fas fa-book-reader"></i>&ensp;Hakkımızda</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}

       <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:profile' %}"><i class="fas fa-user-edit"></i>&nbsp;&nbsp;{{request.user.username}}</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'pet:dashboard' %}"><i class="fas fa-cat"></i>&ensp;Hayvanlarım</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:logout' %}"><i class="fas fa-sign-out-alt"></i>&ensp;Çıkış Yap</a>
      </li>
      <li class="nav-item active">
          
        {% else %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}"><i class="fas fa-user"></i>&ensp;Giriş Yap</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:register' %}"><i class="fas fa-sign-in-alt"></i>&ensp;Kayıt Ol</a>
        </li>
          
        {% endif %}
      
      </ul>
    </div>
  </nav>

  <script src="https://kit.fontawesome.com/e427689c7c.js" crossorigin="anonymous"></script>